In [1]:

# CORE DATA MANIPULATION & IMPORT LIBRARIES
import pandas as pd          # Data manipulation, cleaning, and analysis using DataFrames
import numpy as np           # Numerical computing and handling missing values (NaN)
import glob                  # Finds files matching a specific pattern (e.g., "Coffee-*.xlsx")
from datetime import datetime    # Creates, formats, and manipulates date and time objects
from pathlib import Path         # Modern and object-oriented file path handling
# DATA VISUALIZATION LIBRARIES
import plotly.express as px       # Creates interactive and visually appealing charts
# NOTEBOOK CONFIGURATION
import warnings
warnings.filterwarnings('ignore')    # Suppresses unnecessary warning messages for cleaner output
# Displays Matplotlib plots directly inside the Jupyter Notebook
%matplotlib inline

i have different dataset with the same name so it must be merg to gether

In [2]:
# 1. Find all Excel files whose names start with "Coffee-"
excel_files = sorted(glob.glob("Coffee-*.xlsx"))

# 2. Read each Excel file and store the data in a list of DataFrames
df_list = [pd.read_excel(file) for file in excel_files]

# 3. Combine all DataFrames into a single DataFrame
df = pd.concat(df_list, ignore_index=True)

# 4. Save the combined DataFrame as a CSV file
# index=False prevents pandas from writing row index numbers into the CSV
df.to_csv("all_combined_coffee_data.csv", index=False)

**Data overview**
An overview is a brief general explanation or summary of a topic.
It gives the main idea without detailed information.

In [3]:
# 5. Display the first 5 rows of the combined dataset
df.head()

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Trade Date,Symbol,Warehouse,Production Year,Opening Price,Closing Price,High,Low,Change,Persetntage Change,Volume (Ton)
2,2012-01-02 00:00:00,WYKQ2,BG,2004,"1,175.00",0.00,"1,175.00","1,175.00",0,0.0,28.29
3,2012-01-03 00:00:00,WYKQ2,BG,2004,"1,175.00",0.00,"1,175.00","1,175.00",0,0.0,10.8
4,2012-01-04 00:00:00,WYKQ2,BG,2004,"1,180.00",0.00,"1,180.00","1,180.00",0,0.0,6.61

In [4]:
# 1. Set the second row as the column headers
df.columns = df.iloc[1]

# 2. Remove the first two rows from the DataFrame
df = df.iloc[2:]

# 3. Reset the DataFrame index
df.reset_index(drop=True, inplace=True)

# 4. Display the first five rows of the cleaned DataFrame
df.head(5)

1,Trade Date,Symbol,Warehouse,Production Year,Opening Price,Closing Price,High,Low,Change,Persetntage Change,Volume (Ton)
0,2012-01-02 00:00:00,WYKQ2,BG,2004,"1,175.00",0.00,"1,175.00","1,175.00",0,0.0,28.29
1,2012-01-03 00:00:00,WYKQ2,BG,2004,"1,175.00",0.00,"1,175.00","1,175.00",0,0.0,10.8
2,2012-01-04 00:00:00,WYKQ2,BG,2004,"1,180.00",0.00,"1,180.00","1,180.00",0,0.0,6.61
3,2012-01-06 00:00:00,WYKQ2,BG,2004,"1,175.00",0.00,"1,175.00","1,175.00",0,0.0,8.99
4,2012-01-12 00:00:00,WYKQ2,BG,2004,"1,293.00",0.00,"1,293.00","1,280.00",0,0.0,18

In [5]:
df.columns ## show all columns

Index(['Trade Date', 'Symbol', 'Warehouse', 'Production Year', 'Opening Price',
       'Closing Price', 'High', 'Low', 'Change', 'Persetntage Change',
       'Volume (Ton)'],
      dtype='object', name=1)

**some descripition about the rows of the data set**
 Column Name           |Description                                                    
|**Trade Date**         The date when the coffee trade occurred.                      
 **Symbol**            The identifier or code representing the coffee product.       
 **Warehouse**          The storage location where the coffee was recorded.           
 **Production Year**    The year when the coffee was produced/harvested.              
**Opening Price**      The initial coffee price at the beginning of the trading day. 
 **Closing Price**      The final coffee price at the end of the trading day.         
 **High**               The highest coffee price reached during the trading day.      
 **Low**               The lowest coffee price reached during the trading day.       
 **Change**             The difference between opening and closing prices.            
 **Percentage Change**  The percentage increase or decrease in coffee price.          
 **Volume (Ton)**       The total quantity of coffee traded, measured in tons.

In [6]:
df.shape

(91437, 11)

In [7]:
## understand the structure and data types of the dataset
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 91437 entries, 0 to 91436
Data columns (total 11 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Trade Date          91430 non-null  object
 1   Symbol              91430 non-null  object
 2   Warehouse           91430 non-null  object
 3   Production Year     91430 non-null  object
 4   Opening Price       91430 non-null  object
 5   Closing Price       91430 non-null  object
 6   High                91430 non-null  object
 7   Low                 91430 non-null  object
 8   Change              91430 non-null  object
 9   Persetntage Change  91430 non-null  object
 10  Volume (Ton)        91430 non-null  object
dtypes: object(11)
memory usage: 7.7+ MB

In [8]:
df.describe() ## show statistics

1,Trade Date,Symbol,Warehouse,Production Year,Opening Price,Closing Price,High,Low,Change,Persetntage Change,Volume (Ton)
count,91430,91430,91430,91430,91430,91430,91430,91430,91430,91430,91430.0
unique,1937,720,25,11,2135,2312,2186,2116,458,81,6175.0
top,2013-04-02 00:00:00,LUBP4,HW,2004,900.00,0.00,900.00,900.00,0,0.0%,5.1
freq,96,1482,17235,13251,1489,10490,1422,1481,25411,33654,11828.0

**Data cleaning**
Data cleaning is the process of preparing raw data by identifying and fixing errors, missing values, duplicate records, and inconsistent formats. It improves data quality and ensures the dataset is accurate, consistent, and ready for analysis and visualization.

In [9]:
#  DATA CLEANING & STANDARDIZATION
# Handle possible column name spelling variations safely:
# - Check if the misspelled column exists
# - If not, use the correctly spelled column name
df["Persetntage Change"] = df.get(
    "Persetntage Change",
    df.get("Percentage Change")
)
# Rename the misspelled column to the correct column name
# This improves consistency for later analysis and visualization
df = df.rename(
    columns={
        "Persetntage Change": "Percentage Change"
    }
)

check missing value

In [10]:
## check missing values
df.isnull().sum()

1
Trade Date           7
Symbol               7
Warehouse            7
Production Year      7
Opening Price        7
Closing Price        7
High                 7
Low                  7
Change               7
Percentage Change    7
Volume (Ton)         7
dtype: int64

drop and manipulate missing value

In [11]:
## fill missing values
# 1. Drop rows where ALL columns are completely empty (NaN)
# This removes structural blank rows often imported from Excel files.
df.dropna(how='all', inplace=True)

# 2. Verify if the missing values have been resolved
print("Missing values after dropping empty rows:")
print(df.isnull().sum())

Missing values after dropping empty rows:
1
Trade Date           0
Symbol               0
Warehouse            0
Production Year      0
Opening Price        0
Closing Price        0
High                 0
Low                  0
Change               0
Percentage Change    0
Volume (Ton)         0
dtype: int64

show duplication

In [12]:
df.duplicated().sum() ## show duplicate rows

np.int64(6)

identify and remove duplication

In [13]:
# 1. Identify and inspect the duplicated rows before removing them
# This keeps the first occurrence and shows you exactly what is being deleted.
duplicate_rows = df[df.duplicated(keep='first')]
print(f"Total duplicate rows found: {len(duplicate_rows)}")
print(duplicate_rows.head())

# 2. Remove the duplicate rows
# 'keep="first"' ensures the original record stays, and 'inplace=True' applies it directly to the dataframe.
df.drop_duplicates(keep='first', inplace=True)

# 3. Verify that duplicates have been completely removed
# This should now return 0.
print(f"Remaining duplicates: {df.duplicated().sum()}")

Total duplicate rows found: 6
1      Trade Date  Symbol  Warehouse  Production Year  Opening Price  \
20984  Trade Date  Symbol  Warehouse  Production Year  Opening Price
32024  Trade Date  Symbol  Warehouse  Production Year  Opening Price
43760  Trade Date  Symbol  Warehouse  Production Year  Opening Price
54696  Trade Date  Symbol  Warehouse  Production Year  Opening Price
66710  Trade Date  Symbol  Warehouse  Production Year  Opening Price

1      Closing Price  High  Low  Change   Percentage Change  Volume (Ton)
20984  Closing Price  High  Low  Change  Persetntage Change  Volume (Ton)
32024  Closing Price  High  Low  Change  Persetntage Change  Volume (Ton)
43760  Closing Price  High  Low  Change  Persetntage Change  Volume (Ton)
54696  Closing Price  High  Low  Change  Persetntage Change  Volume (Ton)
66710  Closing Price  High  Low  Change  Persetntage Change  Volume (Ton)
Remaining duplicates: 0

In [14]:
df.duplicated().sum()

np.int64(0)

**Feature Engineering**:
Feature engineering is the process of creating new useful variables (features) from existing data to improve analysis and model performance. It helps extract meaningful information and patterns from raw data

In [15]:


# 1. Convert the 'Trade Date' column to Datetime format
# errors='coerce' will transform invalid or unrecognized date formats into NaT (Not a Time) instead of throwing an error.
df['Trade Date'] = pd.to_datetime(df['Trade Date'], errors='coerce')

# 2. Verify that the transformation was successful (Data Type check)
# This should print 'datetime64[ns]' as the data type.
print("Column Data Type:")
print(df['Trade Date'].dtypes)

# 3. Perform Feature Engineering to extract useful columns for the dashboard
# Once converted to Datetime, we can easily extract the year, month name, and day into separate columns.
df['Year'] = df['Trade Date'].dt.year          # Extracts the year component (e.g., 2012)
df['Month'] = df['Trade Date'].dt.month_name() # Extracts the full name of the month (e.g., January)
df['Day'] = df['Trade Date'].dt.day            # Extracts the day component (e.g., 3)

# 4. Display a sample of the updated dataframe
print("\nSample of the transformed data:")
print(df[['Trade Date', 'Year', 'Month', 'Day']].head())

Column Data Type:
datetime64[ns]

Sample of the transformed data:
1 Trade Date    Year    Month   Day
0 2012-01-02  2012.0  January   2.0
1 2012-01-03  2012.0  January   3.0
2 2012-01-04  2012.0  January   4.0
3 2012-01-06  2012.0  January   6.0
4 2012-01-12  2012.0  January  12.0

In [16]:
df.info() ## understand the structure and data types of the dataset after transformation

<class 'pandas.core.frame.DataFrame'>
Index: 91424 entries, 0 to 91436
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Trade Date         91423 non-null  datetime64[ns]
 1   Symbol             91424 non-null  object
 2   Warehouse          91424 non-null  object
 3   Production Year    91424 non-null  object
 4   Opening Price      91424 non-null  object
 5   Closing Price      91424 non-null  object
 6   High               91424 non-null  object
 7   Low                91424 non-null  object
 8   Change             91424 non-null  object
 9   Percentage Change  91424 non-null  object
 10  Volume (Ton)       91424 non-null  object
 11  Year               91423 non-null  float64
 12  Month              91423 non-null  object
 13  Day                91423 non-null  float64
dtypes: datetime64[ns](1), float64(2), object(11)
memory usage: 10.5+ MB

remove unnecessarythings and convort suitable format

In [17]:

# Convert Production Year column to a clean integer format


df["Production Year"] = (
    df["Production Year"]
    .astype(str)          # Convert values to string for text cleaning
    .str.strip()          # Remove leading and trailing spaces
)

df["Production Year"] = pd.to_numeric(
    df["Production Year"],
    errors="coerce"       # Convert invalid values to missing values (NaN)
).astype("Int64")         # Store as nullable integer type

# Clean and convert numeric columns
numeric_cols = [
    "Opening Price",
    "Closing Price",
    "High",
    "Low",
    "Change",
    "Percentage Change",
    "Volume (Ton)"
]
for col in numeric_cols:

    # Convert column values to string for consistent cleaning
    df[col] = df[col].astype(str)

    # Remove unnecessary spaces from values
    df[col] = df[col].str.strip()

    # Remove commas from numbers (e.g., 1,000 → 1000)
    df[col] = df[col].str.replace(",", "", regex=False)

    # Remove percentage symbols (e.g., 5% → 5)
    df[col] = df[col].str.replace("%", "", regex=False)

    # Remove hidden non-breaking spaces
    df[col] = df[col].str.replace("\xa0", "", regex=False)

    # Remove all remaining spaces inside values
    df[col] = df[col].str.replace(r"\s+", "", regex=True)

    # Convert cleaned values into numeric format
    df[col] = pd.to_numeric(
        df[col],
        errors="coerce"   # Replace invalid values with NaN
    )

# Create new date-based features

# Extract year from Trade Date
df["Year"] = df["Trade Date"].dt.year.astype("Int64")

# Extract month name from Trade Date
df["Month"] = df["Trade Date"].dt.month_name()

# Extract day from Trade Date
df["Day"] = df["Trade Date"].dt.day.astype("Int64")

# Check final dataset information

print(df.info())

<class 'pandas.core.frame.DataFrame'>
Index: 91424 entries, 0 to 91436
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Trade Date         91423 non-null  datetime64[ns]
 1   Symbol             91424 non-null  object
 2   Warehouse          91424 non-null  object
 3   Production Year    91423 non-null  Int64
 4   Opening Price      91423 non-null  float64
 5   Closing Price      91423 non-null  float64
 6   High               91423 non-null  float64
 7   Low                91423 non-null  float64
 8   Change             91423 non-null  float64
 9   Percentage Change  91423 non-null  float64
 10  Volume (Ton)       91423 non-null  float64
 11  Year               91423 non-null  Int64
 12  Month              91423 non-null  object
 13  Day                91423 non-null  Int64
dtypes: Int64(3), datetime64[ns](1), float64(7), object(3)
memory usage: 10.7+ MB
None

In [18]:
df[df.isnull().any(axis=1)]

1,Trade Date,Symbol,Warehouse,Production Year,Opening Price,Closing Price,High,Low,Change,Percentage Change,Volume (Ton),Year,Month,Day
10362,NaT,Symbol,Warehouse,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,NaN,<NA>

In [19]:
df = df.dropna().reset_index(drop=True)

In [20]:
df[df.isnull().any(axis=1)]

Empty DataFrame
Columns: [Trade Date, Symbol, Warehouse, Production Year, Opening Price, Closing Price, High, Low, Change, Percentage Change, Volume (Ton), Year, Month, Day]
Index: []

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 91423 entries, 0 to 91422
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Trade Date         91423 non-null  datetime64[ns]
 1   Symbol             91423 non-null  object
 2   Warehouse          91423 non-null  object
 3   Production Year    91423 non-null  Int64
 4   Opening Price      91423 non-null  float64
 5   Closing Price      91423 non-null  float64
 6   High               91423 non-null  float64
 7   Low                91423 non-null  float64
 8   Change             91423 non-null  float64
 9   Percentage Change  91423 non-null  float64
 10  Volume (Ton)       91423 non-null  float64
 11  Year               91423 non-null  Int64
 12  Month              91423 non-null  object
 13  Day                91423 non-null  Int64
dtypes: Int64(3), datetime64[ns](1), float64(7), object(3)
memory usage: 10.0+ MB

**KPI** stands for Key Performance Indicator.

A KPI is a number or metric that shows how well something is performing. It gives users a quick summary of the most important information before they look at charts

In [22]:

# KPI Calculations

# Total Trading Volume
total_volume = df["Volume (Ton)"].sum()

# Average Opening Price
avg_opening = df["Opening Price"].mean()

# Average Closing Price
avg_closing = df["Closing Price"].mean()

# Highest Price
highest_price = df["High"].max()

# Lowest Price
lowest_price = df["Low"].min()

# Average Percentage Change
avg_change = df["Percentage Change"].mean()

# Number of Warehouses
total_warehouses = df["Warehouse"].nunique()

# Number of Symbols
total_symbols = df["Symbol"].nunique()

# Number of Trading Days
trading_days = df["Trade Date"].nunique()

In [23]:
# Filter out records where Closing Price is 0 or less
df_cleaned = df[df["Closing Price"] > 0].copy()

# Print status check
print(f"Total records before cleaning: {len(df):,}")
print(f"Total records after cleaning: {len(df_cleaned):,}")
print(f"Total records removed: {len(df) - len(df_cleaned):,}")

# Export cleaned data
df_cleaned.to_csv("cleaned_coffee_data.csv", index=False)

Total records before cleaning: 91,423
Total records after cleaning: 80,933
Total records removed: 10,490

In [24]:


# Load the cleaned dataset into a pandas DataFrame
df = pd.read_csv("cleaned_coffee_data.csv")

# Convert the 'Trade Date' column to datetime objects
# 'errors="coerce"' replaces any unparseable or invalid dates with NaT (Not a Time/null)
df["Trade Date"] = pd.to_datetime(df["Trade Date"], errors="coerce")

**Data Visualization**

Data visualization is the process of presenting data in graphical and visual formats such as charts, graphs, maps, and dashboards. It helps users understand complex data quickly, identify trends and patterns, detect outliers, and make informed decisions. Effective data visualization transforms raw data into meaningful insights, making information easier to interpret and communicate. Common visualization types include bar charts, line charts, pie charts, scatter plots, and dashboards.

show Coffee Closing Price Trend (Monthly Average)

In [25]:

# 4. Sort chronologically by date
df_cleaned = df_cleaned.sort_values("Trade Date")

# 5. Aggregate data by Month using average closing price
df_monthly = (
    df_cleaned.set_index("Trade Date")
    .resample("ME")["Closing Price"]
    .mean()
    .reset_index()
)

# 6. Create the Plotly line chart
fig_closing = px.line(
    df_monthly,
    x="Trade Date",
    y="Closing Price",
    title="Closing Price Trend Over Time",
    labels={
        "Trade Date": "Trade Date",
        "Closing Price": "Closing Price (ETB)",
    },
)

# 7. Improve graph layout and styling
fig_closing.update_layout(
    template="plotly_white",
    title={
        "text": "Coffee Closing Price Trend (Monthly Average)",
        "x": 0.5,
        "xanchor": "center",
    },
    xaxis_title="Trade Date",
    yaxis_title="Closing Price (ETB)",
    hovermode="x unified",
    height=500,
)

# 8. Set coffee-brown line styling
fig_closing.update_traces(line=dict(color="#A52A2A", width=3), mode="lines")

# 9. Render the plot in Jupyter Notebook
fig_closing.show()

high vs low trade price

In [26]:


# 1. Convert 'Trade Date' to proper pandas datetime format (if not already done)
df['Trade Date'] = pd.to_datetime(df['Trade Date'])

# 2. Sort the data chronologically by date
df = df.sort_values("Trade Date")

# 3. Aggregate data by Month to prevent overplotting (91k rows -> clean trend)
# We take the max of 'High' and the min of 'Low' for each month to see the true market range
df_monthly_range = df.set_index('Trade Date').resample('M').agg({
    'High': 'max',
    'Low': 'min'
}).reset_index()

# 4. Melt the data into long format so Plotly Express can plot multiple lines automatically
df_melted = df_monthly_range.melt(
    id_vars=["Trade Date"], 
    value_vars=["High", "Low"],
    var_name="Price Type", 
    value_name="Price (ETB)"
)

# 5. Create the Multi-Line Chart
fig_high_low = px.line(
    df_melted,
    x="Trade Date",
    y="Price (ETB)",
    color="Price Type", # Creates two distinct lines automatically based on High vs Low
    title="Monthly High vs Low Price Trend",
    color_discrete_map={
        "High": "#228B22",  # Forest Green for High prices
        "Low": "#DC143C"    # Crimson Red for Low prices
    },
    labels={"Trade Date": "Trade Date", "Price (ETB)": "Price (ETB)"}
)

# 6. Improve the dashboard layout appearance
fig_high_low.update_layout(
    template="plotly_white",
    title={
        "text": "📈 Coffee Price Range Trend (Monthly High vs Low)",
        "x": 0.5,
        "xanchor": "center"
    },
    xaxis_title="Trade Date",
    yaxis_title="Price (ETB)",
    hovermode="x unified", # Shows both High and Low values together when hovering over a date
    height=500
)

# 7. Make the lines smoother and distinct
fig_high_low.update_traces(
    line=dict(width=2.5),
    mode="lines"
)

# 8. Display the chart in your Jupyter Notebook
fig_high_low.show()

visualize trade volume by warehouse

In [27]:

# 1. DATA AGGREGATION & SORTING
# Group records by 'Warehouse' and compute the total trading volume for each location
warehouse_volume = (
    df.groupby("Warehouse")["Volume (Ton)"].sum().reset_index()
)

# Sort the warehouses in descending order based on total volume (highest to lowest)
warehouse_volume = warehouse_volume.sort_values(
    by="Volume (Ton)", ascending=False
)

# 2. CREATE VERTICAL BAR CHART

fig_warehouse = px.bar(
    warehouse_volume,
    x="Warehouse",  # Warehouse locations on X-axis
    y="Volume (Ton)",  # Total volume metric on Y-axis
    title="Trading Volume by Warehouse",  # Fallback chart title
    labels={
        "Warehouse": "Warehouse",
        "Volume (Ton)": "Trading Volume (Ton)",
    },  # Custom axis labels
    text_auto=".2s",  # Format large numerical values into concise SI suffixes (e.g., 1.2M, 450k)
)

# 3. CUSTOMIZE DASHBOARD LAYOUT & APPEARANCE
fig_warehouse.update_layout(
    template="plotly_white",  # Apply a clean, minimalist white theme
    title={
        "text": "Trading Volume by Warehouse",  # Main title text
        "x": 0.5,  # Horizontally center the title (0 = left, 1 = right)
        "xanchor": "center",  # Set title anchor point to the center
    },
    xaxis_title="Warehouse",  # X-axis label
    yaxis_title="Trading Volume (Ton)",  # Y-axis label
    height=500,  # Set vertical chart height in pixels
)

# 4. STYLE BAR CHART TRACES
fig_warehouse.update_traces(
    marker_color="#8B4513",  # Apply a Saddle Brown color matching the coffee dashboard theme
    textposition="outside",  # Position formatted text values neatly above each bar
)

# 5. DISPLAY THE PLOT
# Render the interactive bar chart figure inside Jupyter Notebook
fig_warehouse.show()

visualze  monthly coffee tranding volume trend

In [28]:

# 1. DATE PREPROCESSING & SORTING
# Convert 'Trade Date' column into pandas datetime objects for time-based operations
df["Trade Date"] = pd.to_datetime(df["Trade Date"])

# Sort the entire dataset chronologically in ascending order
df = df.sort_values("Trade Date")

# 2. DATA AGGREGATION & RESAMPLING
# Group data by calendar month end ('M') and sum total trading volumes per month
# This resamples large datasets into a structured monthly time-series DataFrame
df_monthly_volume = (
    df.set_index("Trade Date")
    .resample("M")["Volume (Ton)"]
    .sum()
    .reset_index()
)

# 3. CREATE VERTICAL BAR CHART
fig_monthly_volume = px.bar(
    df_monthly_volume,
    x="Trade Date",  # Monthly date timeline on X-axis
    y="Volume (Ton)",  # Aggregated trading volume on Y-axis
    title="Monthly Trading Volume Trend",  # Fallback chart title
    labels={
        "Trade Date": "Timeline",
        "Volume (Ton)": "Trading Volume (Tons)",
    },  # Custom axis labels
    text_auto=".2s",  # Format large numerical values into concise SI suffixes (e.g., 1.2M, 450k)
)
# 4. CUSTOMIZE DASHBOARD LAYOUT & APPEARANCE
fig_monthly_volume.update_layout(
    template="plotly_white",  # Apply a clean, minimalist white theme
    title={
        "text": "Monthly Coffee Trading Volume Trend",  # Centered title text
        "x": 0.5,  # Horizontally center the title (0 = left, 1 = right)
        "xanchor": "center",  # Anchor point for precise title alignment
    },
    xaxis_title="Timeline (Months)",  # X-axis label
    yaxis_title="Trading Volume (Tons)",  # Y-axis label
    height=500,  # Set vertical chart height in pixels
)

# 5. STYLE BAR CHART TRACES
fig_monthly_volume.update_traces(
    marker_color="#8B4513",  # Apply a Saddle Brown color matching the coffee dashboard theme
    textposition="outside",  # Position formatted text values neatly above each bar
)
# 6. DISPLAY THE PLOT
# Render the interactive bar chart figure inside Jupyter Notebook
fig_monthly_volume.show()

In [29]:
df.columns

Index(['Trade Date', 'Symbol', 'Warehouse', 'Production Year', 'Opening Price',
       'Closing Price', 'High', 'Low', 'Change', 'Percentage Change',
       'Volume (Ton)', 'Year', 'Month', 'Day'],
      dtype='object')

In [30]:

# 1. DATE PREPROCESSING & FEATURE EXTRACTION
# Convert 'Trade Date' column into pandas datetime objects for time-based operations
df["Trade Date"] = pd.to_datetime(df["Trade Date"])
# Extract the calendar year from the datetime objects into a dedicated column
df["Year"] = df["Trade Date"].dt.year
# 2. DATA AGGREGATION
# Group records by year and compute the mean closing price for each year
df_yearly_price = df.groupby("Year")["Closing Price"].mean().reset_index()

# Sort the aggregated dataset chronologically in ascending order
df_yearly_price = df_yearly_price.sort_values("Year", ascending=True)
# 3. CREATE VERTICAL BAR CHART

fig_yearly_price = px.bar(
    df_yearly_price,
    x="Year",  # Categorical feature on X-axis
    y="Closing Price",  # Metric feature on Y-axis
    title="Average Closing Price by Production Year",  # Fallback chart title
    labels={
        "Year": "Production Year",
        "Closing Price": "Average Closing Price (ETB)",
    },  # Custom axis labels
    text_auto=".2f",  # Automatically display values formatted to 2 decimal places on bars
)

# 4. CUSTOMIZE DASHBOARD LAYOUT & AXES
fig_yearly_price.update_layout(
    template="plotly_white",  # Apply a clean, minimalist white theme
    title={
        "text": "Average Closing Price by Production Year",  # Centered title text
        "x": 0.5,  # Horizontally center the title (0 = left, 1 = right)
        "xanchor": "center",  # Anchor point for precise title alignment
    },
    xaxis_title="Production Year",  # X-axis title
    yaxis_title="Average Closing Price (ETB)",  # Y-axis title
    xaxis=dict(
        type="category"
    ),  # Treat years as discrete categorical labels rather than continuous numeric values
    height=500,  # Set vertical chart height in pixels
)

# 5. STYLE BAR CHART TRACES
fig_yearly_price.update_traces(
    marker_color="#4169E1",  # Apply a consistent Royal Blue color to bars
    textposition="outside",  # Position the numerical value labels neatly above each bar
)

# 6. DISPLAY THE PLOT
# Render the interactive bar chart figure inside Jupyter Notebook
fig_yearly_price.show()

In [ ]:

# ETHIOPIA COFFEE MARKET DASHBOARD
# Developed By: Awoke Tiruneh
# Bahir Dar University
# Data Science Project
# Import Required Libraries
# Import Streamlit library for building the interactive dashboard
import streamlit as st
# Import Pandas for data loading, cleaning, and analysis
import pandas as pd
# Import Plotly Express for creating interactive charts with simple syntax
import plotly.express as px
# Import Plotly Graph Objects for advanced and customized visualizations
import plotly.graph_objects as go
st.set_page_config(
    page_title="Ethiopia Coffee Market Dashboard",  # Title shown in the browser tab
    page_icon="☕",                                  # Icon displayed in the browser tab
    layout="wide",                                  # Use full screen width for dashboard content
    initial_sidebar_state="expanded"                # Open sidebar automatically when app starts
)
# Custom CSS Styling
# Modify Streamlit default layout:
# - Add small left and right margins
# - Use full available screen width for dashboard components
st.markdown(
    """
<style>
/* 1. Main Page Margin and Padding Adjustments */
.block-container {
    padding-top: 0rem !important; /* - Reduce top padding */
    padding-bottom: 0rem !important;
    padding-left: 0rem !important;
    padding-right: 0rem !important;
    max-width: 100% !important;
}
/* 2. Narrowing the large gap between vertical elements */
div[data-testid="stVerticalBlock"] {
    gap: 0rem !important;
}
div[data-testid="stVerticalBlock"] > div {
    gap: 0rem !important;
    margin-bottom: 0.1rem !important;
}
/* 3. Removing extra space around Headings (h1, h2, h3) */
h1, h2, h3 {
    margin-top: 0.8rem !important;
    margin-bottom: 0.2rem !important;
    padding-top: 0.2rem !important;
    padding-bottom: 0.2rem !important;
}
/* 4. Narrowing the gap between horizontal columns (for KPIs) */
div[data-testid="stHorizontalBlock"] {
    gap: 0.3rem !important;
}
</style>
""",
    unsafe_allow_html=True,
)
st.markdown(
    """
<div style="background-color: #4A2C11; padding: 15px; border-radius: 6px; color: white; margin-bottom: 2px;">   
    <h1 style="margin: 0; color: white; font-size: 2rem;">☕ Ethiopia Coffee Market Dashboard</h1>   
    <p style="margin: 5px 0 0 0; color: #F5E6CA; font-size: 1.05rem;">   
        Analytical dashboard — Use the filters on the left to explore prices, trading volume and market trends.
    </p>
</div>
""",
    unsafe_allow_html=True,
)  

# Apply custom CSS to remove Streamlit's default top header
# This creates a cleaner dashboard interface without the default toolbar area
st.markdown("""
<style>
header[data-testid="stHeader"]{   /* Hide Streamlit Default Header*/
    display:none;  /* Remove the default Streamlit header from the page */
}
</style>
""", unsafe_allow_html=True)  # Allow custom CSS styling in Streamlit
# Load Cleaned Coffee Dataset with Caching
@st.cache_data  # Cache dataset in RAM to optimize dashboard responsiveness
def load_data():
    # Read the preprocessed coffee market dataset
    df = pd.read_csv("cleaned_coffee_data.csv")
    # Ensure Year and Day columns are cast to numeric data types
    df["Year"] = pd.to_numeric(df["Year"], errors="coerce")
    df["Day"] = pd.to_numeric(df["Day"], errors="coerce")
    return df
# Load cached data into dataframe
df = load_data()
# Sidebar Filters
# Filters Title
st.sidebar.header("🔎 Filters")
# Space after button
st.sidebar.markdown("<br>", unsafe_allow_html=True)
# Reset Button
if st.sidebar.button("🔄 Reset Filters"):
    st.session_state["year_filter"] = "All"
    st.session_state["month_filter"] = "All"
    st.session_state["day_filter"] = "All"
    st.session_state["warehouse_filter"] = "All"
    st.session_state["symbol_filter"] = "All"
    st.rerun()
# Year Filter
year_options = sorted(
    df["Year"].dropna().astype(int).unique().tolist()
)
selected_year = st.sidebar.selectbox(
    "Select Year",
    options=["All"] + year_options,
    key="year_filter"
)
# Month Filter
month_options = sorted(
    df["Month"].dropna().unique().tolist()
)
selected_month = st.sidebar.selectbox(
    "Select Month",
    options=["All"] + month_options,
    key="month_filter"
)
# Day Filter
day_options = sorted(
    df["Day"].dropna().astype(int).unique().tolist()
)
selected_day = st.sidebar.selectbox(
    "Select Day",
    options=["All"] + day_options,
    key="day_filter"
)
# Warehouse Filter
warehouse_options = sorted(
    df["Warehouse"].dropna().unique().tolist()
)

selected_warehouse = st.sidebar.selectbox(
    "Select Warehouse",
    options=["All"] + warehouse_options,
    key="warehouse_filter"
)
# Coffee Symbol Filter
symbol_options = sorted(
    df["Symbol"].dropna().unique().tolist()
)
selected_symbol = st.sidebar.selectbox(
    "Select Coffee Symbol",
    options=["All"] + symbol_options,
    key="symbol_filter"
)
# Apply Selected Filters
filtered_df = df.copy()
# Filter by Year
if selected_year != "All":
    filtered_df = filtered_df[
        filtered_df["Year"] == selected_year
    ]
# Filter by Month
if selected_month != "All":
    filtered_df = filtered_df[
        filtered_df["Month"] == selected_month
    ]
# Filter by Day
if selected_day != "All":
    filtered_df = filtered_df[
        filtered_df["Day"] == selected_day
    ]
# Filter by Warehouse
if selected_warehouse != "All":
    filtered_df = filtered_df[
        filtered_df["Warehouse"] == selected_warehouse
    ]
# Filter by Coffee Symbol
if selected_symbol != "All":
    filtered_df = filtered_df[
        filtered_df["Symbol"] == selected_symbol
    ]
# Display Number of Filtered Records
st.sidebar.success(
    f"Total Records: {len(filtered_df):,}"
)
# Custom Sidebar Styling
st.markdown("""
<style>

/* Sidebar Background Color */
section[data-testid="stSidebar"] {
    background-color: #4A2C11 !important;
    border-right: 0px solid #DDD;
}

/* Sidebar Header Color */
section[data-testid="stSidebar"] h1,
section[data-testid="stSidebar"] h2,
section[data-testid="stSidebar"] h3 {
    color: white !important;
}

/* Sidebar Widget Labels */
section[data-testid="stSidebar"] label[data-testid="stWidgetLabel"] p {
    color: #F5E6CA !important;
    font-weight: 600 !important;
    font-size: 1rem !important;
}

/* Sidebar Text */
section[data-testid="stSidebar"] label,
section[data-testid="stSidebar"] p,
section[data-testid="stSidebar"] span {
    color: #F5E6CA !important;
}

/* Total Records Box Text */
section[data-testid="stSidebar"] .stAlert {
    color: white !important;
}

</style>
""", unsafe_allow_html=True)

# Compact KPI Styling

st.markdown("""
<style>

/* KPI Cards */
div[data-testid="stMetric"] {
    background-color: #D4AF37;
    padding: 2px 2px !important;
    border-radius: 10px;
    border: 1px solid #B8860B;
    box-shadow: 0px 2px 5px rgba(0,0,0,0.15);
    min-height: 5px !important;
}
/* KPI Label */
div[data-testid="stMetricLabel"] {
    color: #3E2723 !important;
    font-size: 8px !important;
    font-weight: 600 !important;
    line-height: 1.2 !important;
}
/* KPI Value */
div[data-testid="stMetricValue"] {
    color: #2E1B0E !important;
    font-size: 15px !important;
    font-weight: 700 !important;
    line-height: 1.2 !important;
}
/* Reduce column spacing */
div[data-testid="column"] {
    padding-left: 0px;
    padding-right: 0px;
}
</style>
""", unsafe_allow_html=True)
# KPI Section Header
st.markdown("""
<div style="
    background-color:#1B5E20;
    color:white;
    font-size:15px;
    font-weight:700;
    padding:6px 10px;
    border-radius:8px;
    text-align:center;
    margin-top:0px;
    margin-bottom:15px;
">
☕ Key Performance Indicators (KPIs) Overview
</div>
""", unsafe_allow_html=True)
# KPI Calculations
# Aggregate summary metrics from the filtered DataFrame
total_volume = filtered_df["Volume (Ton)"].sum()
avg_opening = filtered_df["Opening Price"].mean()
avg_closing = filtered_df["Closing Price"].mean()
highest_price = filtered_df["High"].max()
lowest_price = filtered_df["Low"].min()
total_warehouses = filtered_df["Warehouse"].nunique()
total_symbols = filtered_df["Symbol"].nunique()
# Dynamic YoY (Year-over-Year) Price Growth Calculation
# Year-over-Year Growth Calculation
yoy_str = "N/A"
try:
    if selected_year == "All":

        # Compare latest year vs previous year
        yearly_avg = (
            filtered_df.groupby("Year")["Closing Price"]
            .mean()
            .reset_index()
            .sort_values("Year")
        )

        if len(yearly_avg) >= 2:
            latest_price = yearly_avg.iloc[-1]["Closing Price"]
            prev_price = yearly_avg.iloc[-2]["Closing Price"]

            if prev_price > 0:
                growth = ((latest_price - prev_price) / prev_price) * 100
                yoy_str = f"{growth:+.2f}%"

    else:
        current_year_int = int(selected_year)
        prev_year_int = current_year_int - 1

        # Start from full dataset
        temp_df = df.copy()

        # Keep other active filters
        if selected_month != "All":
            temp_df = temp_df[temp_df["Month"] == selected_month]

        if selected_day != "All":
            temp_df = temp_df[temp_df["Day"] == selected_day]

        if selected_warehouse != "All":
            temp_df = temp_df[temp_df["Warehouse"] == selected_warehouse]

        if selected_symbol != "All":
            temp_df = temp_df[temp_df["Symbol"] == selected_symbol]

        # Calculate average closing price
        curr_avg = temp_df[
            temp_df["Year"] == current_year_int
        ]["Closing Price"].mean()

        prev_avg = temp_df[
            temp_df["Year"] == prev_year_int
        ]["Closing Price"].mean()

        if (
            pd.notnull(curr_avg)
            and pd.notnull(prev_avg)
            and prev_avg > 0
        ):
            growth = ((curr_avg - prev_avg) / prev_avg) * 100
            yoy_str = f"{growth:+.2f}%"

except Exception:
    yoy_str = "N/A"

# KPI Cards Display - Single Row (8 KPIs)

col1, col2, col3, col4, col5, col6, col7, col8 = st.columns(8)

with col1:
    st.metric("📦 Total Volume", f"{total_volume:,.0f} Ton")

with col2:
    st.metric("💰 Avg Opening", f"{avg_opening:,.2f} ETB")

with col3:
    st.metric("💵 Avg Closing", f"{avg_closing:,.2f} ETB")

with col4:
    st.metric("📈 Highest Price", f"{highest_price:,.2f} ETB")

with col5:
    st.metric("📉 Lowest Price", f"{lowest_price:,.2f} ETB")

with col6:
    st.metric("🏢 Warehouses", total_warehouses)

with col7:
    st.metric("☕ Symbols", total_symbols)

with col8:
    st.metric("📊 YoY Growth", yoy_str)
# 🎯 MARKET INSIGHTS SECTION (ALIGNED WITH GRAPH ORDER)

st.markdown("""
<div style="
    background-color:#8B0000;
    color:white;
    font-size:15px;
    font-weight:700;
    padding:8px 12px;
    border-radius:8px;
    text-align:center;
    margin-top:0px;
    margin-bottom:15px;
">
☕ Market insight summary
</div>
""", unsafe_allow_html=True)


# 1. Helper Function for Insight Cards
def create_blue_card(
    title,
    value,
    subtext="",
    bg_color="#0F172A",
    border_color="#3B82F6",
    text_color="#F8FAFC",
    sub_color="#94A3B8",
):
    subtext_html = (
        f'<p style="margin: 2px 0 0 0; font-size: 12px; color: {border_color}; font-weight: 700; line-height: 1.1;">{subtext}</p>'
        if subtext
        else ""
    )

    html_code = f"""
    <div style="
        background-color:  #4A2C11;
        border-left: 4px solid {border_color};
        padding: 6px 0px;
        border-radius: 6px;
        box-shadow: 0 2px 4px rgba(0,0,0,0.15);
        margin-bottom: 10px;
        margin-top: 0.8rem !important;
        height: 50%;
        display: flex;
        flex-direction: column;
        justify-content: center;
    ">
        <p style="margin: 0; font-size: 15px; color: {sub_color}; font-weight: 600; line-height: 0;">{title}</p>
        <h3 style="margin: 2px 0; color: {text_color}; font-size: 15px; font-weight: bold; line-height: 1.1;">{value}</h3>
        {subtext_html}
    </div>
    """
    return st.markdown(html_code, unsafe_allow_html=True)
# 2. CALCULATIONS & DISPLAY (MATCHING GRAPH ORDER)
if not filtered_df.empty:
    # 1. Best Price Year & Price Data
    yearly_price = filtered_df.groupby("Year")["Closing Price"].mean().reset_index()
    if not yearly_price.empty:
        best_price_year = yearly_price.loc[yearly_price["Closing Price"].idxmax(), "Year"]
        highest_avg_price = yearly_price["Closing Price"].max()
    else:
        best_price_year, highest_avg_price = "N/A", 0

    # 2. Peak Volume Year
    yearly_volume = filtered_df.groupby("Year")["Volume (Ton)"].sum().reset_index()
    if not yearly_volume.empty:
        peak_vol_year = yearly_volume.loc[yearly_volume["Volume (Ton)"].idxmax(), "Year"]
        peak_volume = yearly_volume["Volume (Ton)"].max()
    else:
        peak_vol_year, peak_volume = "N/A", 0

    # 3. Peak Month
    monthly_price = filtered_df.groupby("Month")["Closing Price"].mean().reset_index()
    if not monthly_price.empty:
        peak_month = monthly_price.loc[monthly_price["Closing Price"].idxmax(), "Month"]
    else:
        peak_month = "N/A"

    # 4. Top Symbol & Top Warehouse
    top_symbol = filtered_df.groupby("Symbol")["Volume (Ton)"].sum().idxmax() if not filtered_df.empty else "N/A"
    top_warehouse = filtered_df.groupby("Warehouse")["Volume (Ton)"].sum().idxmax() if not filtered_df.empty else "N/A"

    # 5. Overall Trend
    if len(yearly_price) > 1:
        first_price = yearly_price["Closing Price"].iloc[0]
        last_price = yearly_price["Closing Price"].iloc[-1]
        trend = "📈 Upward" if last_price >= first_price else "📉 Downward"
    else:
        trend = "➡️ Stable"

    # 6. Gain Ratio
    if "Change" in filtered_df.columns:
        positive_days = (filtered_df["Change"] > 0).sum()
        gain_ratio = (positive_days / len(filtered_df)) * 100
    else:
        gain_ratio = 0

    # 7. Top Gainer Calculation (Replaces Volatility)
    df_gainer_calc = filtered_df.copy()
    if "Percentage Change (%)" not in df_gainer_calc.columns and "Percentage Change" not in df_gainer_calc.columns:
        if "Opening Price" in df_gainer_calc.columns and "Closing Price" in df_gainer_calc.columns:
            df_gainer_calc["Percentage Change (%)"] = (
                (df_gainer_calc["Closing Price"] - df_gainer_calc["Opening Price"]) / df_gainer_calc["Opening Price"]
            ) * 100

    pct_col = "Percentage Change (%)" if "Percentage Change (%)" in df_gainer_calc.columns else "Percentage Change"

    if pct_col in df_gainer_calc.columns:
        avg_gain = df_gainer_calc.groupby("Symbol")[pct_col].mean()
        if not avg_gain.empty:
            top_gainer_symbol = avg_gain.idxmax()
            top_gainer_val = avg_gain.max()
        else:
            top_gainer_symbol, top_gainer_val = "N/A", 0
    else:
        top_gainer_symbol, top_gainer_val = "N/A", 0
        
    # --- DISPLAY CARDS (PERFECTLY ALIGNED WITH GRAPHS 1-8) ---

    c1, c2, c3, c4, c5, c6, c7, c8 = st.columns(8)

    # 1. Matches Graph 1: Top Symbols (Bar Chart)
    with c1:
        create_blue_card(
            "☕ Top Symbol",
            top_symbol,
            "Most Traded",
            "#0F172A", "#3B82F6", "#FFFFFF", "#94A3B8"
        )

    # 2. Matches Graph 2: Yearly Price (Bar Chart)
    with c2:
        create_blue_card(
            "💰 Best Price Year",
            str(best_price_year),
            f"{highest_avg_price:,.0f} ETB",
            "#0F172A", "#3B82F6", "#FFFFFF", "#94A3B8"
        )

    # 3. Matches Graph 3: Price Trend (Line Chart)
    with c3:
        create_blue_card(
            "📈 Price Trend",
            trend,
            "Market Direction",
            "#0F172A", "#3B82F6", "#FFFFFF", "#94A3B8"
        )

    # 4. Matches Graph 4: Warehouse Volume (Bar Chart)
    with c4:
        create_blue_card(
            "🏢 Top Warehouse",
            top_warehouse,
            "Top Location",
            "#0F172A", "#3B82F6", "#FFFFFF", "#94A3B8"
        )

    # 5. Matches Graph 5: High vs Low (Line Chart / Market Sentiment)
    with c5:
        create_blue_card(
            "🟢 Gain Ratio",
            f"{gain_ratio:.1f}%",
            "Positive Days",
            "#1E293B", "#4ADE80", "#FFFFFF", "#CBD5E1"
        )

    # 6. Matches Graph 6: Volume Trend (Bar Chart)
    with c6:
        create_blue_card(
            "📦 Peak Volume Year",
            str(peak_vol_year),
            f"{peak_volume:,.0f} Ton",
            "#1E293B", "#60A5FA", "#FFFFFF", "#CBD5E1"
        )

    # 7. Matches Graph 7: Seasonality (Line Chart)s
    with c7:
        create_blue_card(
            "🗓️ Peak Month",
            str(peak_month),
            "Highest Avg Price",
            "#1E293B", "#60A5FA", "#FFFFFF", "#CBD5E1"
        )

    # 8. Matches Graph 8: Top 5 Gainers (Horizontal Bar Chart)
    with c8:
        create_blue_card(
            "🚀 Top Gainer",
            top_gainer_symbol,
            f"+{top_gainer_val:.2f}% Avg",
            "#1E293B", "#22C55E", "#FFFFFF", "#CBD5E1"
        )

else:
    st.warning("⚠️ No data available for selected filters.")
# 📊 FOUR CHARTS IN ONE ROW
col1, col2, col3, col4 = st.columns(4)
# ☕ Top 10 Coffee Symbols
with col1:
    top_symbols = (
        filtered_df.groupby("Symbol")["Volume (Ton)"]
        .sum()
        .reset_index()
        .sort_values("Volume (Ton)", ascending=False)
        .head(10)
    )

    fig_symbol = px.bar(
        top_symbols,
        x="Symbol",
        y="Volume (Ton)",
        title="☕ Top Symbols"
    )

    fig_symbol.update_layout(
        template="plotly_white",
        height=200,
        margin=dict(t=40, b=5, l=0, r=0),
        plot_bgcolor="#F5F1E8",
        paper_bgcolor="#F5F1E8",
        showlegend=False,
        title_x=0.25,
        yaxis=dict(showgrid=False)
    )
    fig_symbol.update_traces(marker_color="#2C1D11")

    st.plotly_chart(
        fig_symbol,
        use_container_width=True,
        config={"displayModeBar": False}
    )
# 📅 Yearly Market Performance
with col2:
    yearly_market = (
        filtered_df.groupby("Year")
        .agg({
            "Closing Price": "mean",
            "Volume (Ton)": "sum"
        })
        .reset_index()
    )
    fig_yearly = px.bar(
        yearly_market,
        x="Year",
        y="Closing Price",
        title="📅 Yearly Price"
    )
    fig_yearly.update_layout(
        template="plotly_white",
        height=200,
        margin=dict(t=40, b=5, l=0, r=0),
        plot_bgcolor="#F5F1E8",
        paper_bgcolor="#F5F1E8",
        showlegend=False,
        title_x=0.25,
        yaxis=dict(showgrid=False)
    )
    fig_yearly.update_traces(marker_color="#3D2314")

    st.plotly_chart(
        fig_yearly,
        use_container_width=True,
        config={"displayModeBar": False}
    )
# ☕ Closing Price Trend
with col3:

    temp_df = filtered_df.copy()

    temp_df["Trade Date"] = pd.to_datetime(
        temp_df["Trade Date"],
        errors="coerce"
    )

    temp_df = temp_df.dropna(subset=["Trade Date"])

    monthly_price = (
        temp_df
        .set_index("Trade Date")
        .resample("ME")["Closing Price"]
        .mean()
        .reset_index()
    )

    fig_price = px.line(
        monthly_price,
        x="Trade Date",
        y="Closing Price",
        title="📈 Price Trend"
    )

    fig_price.update_layout(
        template="plotly_white",
        height=200,
        margin=dict(t=40, b=20, l=0, r=0),
        plot_bgcolor="#F5F1E8",
        paper_bgcolor="#F5F1E8",
        showlegend=False,
        title_x=0.25,
        yaxis=dict(showgrid=False)
    )
    fig_price.update_traces(
        line=dict(
            color="#121212",
            width=2
        )
    )
    st.plotly_chart(
        fig_price,
        use_container_width=True,
        config={"displayModeBar": False}
    )
# 🏭 Trading Volume by Warehouse
with col4:
    warehouse_volume = (
        filtered_df.groupby("Warehouse")["Volume (Ton)"]
        .sum()
        .reset_index()
        .sort_values("Volume (Ton)", ascending=False)
    )
    fig_warehouse = px.bar(
        warehouse_volume,
        x="Warehouse",
        y="Volume (Ton)",
        title="🏭 Warehouse Volume"
    )

    fig_warehouse.update_layout(
        template="plotly_white",
        height=200,
        margin=dict(t=40, b=5, l=0, r=0),
        plot_bgcolor="#F5F1E8",
        paper_bgcolor="#F5F1E8",
        showlegend=False,
        title_x=0.2,
        yaxis=dict(showgrid=False)
    )
    fig_warehouse.update_traces(
        marker_color="#264653",
    )
    st.plotly_chart(
        fig_warehouse,
        use_container_width=True,
        config={"displayModeBar": False}
    )
# ROW: High-Low Trend | Volume Trend | Seasonality | Volatility
col1, col2, col3, col4 = st.columns(4)
# 📈 1. Monthly High vs Low Price Trend
with col1:

    df_temp = filtered_df.copy()

    df_temp["Trade Date"] = pd.to_datetime(
        df_temp["Trade Date"],
        errors="coerce"
    )

    df_temp = df_temp[
        (df_temp["High"] > 0)
        & (df_temp["Low"] > 0)
    ]

    df_monthly_range = (
        df_temp
        .set_index("Trade Date")
        .resample("ME")
        .agg({
            "High": "max",
            "Low": "min"
        })
        .reset_index()
    )

    df_melted = df_monthly_range.melt(
        id_vars=["Trade Date"],
        value_vars=["High", "Low"],
        var_name="Price Type",
        value_name="Price (ETB)"
    )

    fig_high_low = px.line(
        df_melted,
        x="Trade Date",
        y="Price (ETB)",
        color="Price Type",
        title="📈 High vs Low",
        color_discrete_map={
            "High":"#2A9D8F",
            "Low": "#C87D55",
        }
    )

    fig_high_low.update_layout(
        template="plotly_white",
        height=200,
        plot_bgcolor="#F5F1E8",
        paper_bgcolor="#F5F1E8",
        hovermode="x unified",
        yaxis=dict(showgrid=False),
        title_x=0.15,
        margin=dict(t=40, b=5, l=0, r=0)
    )
    fig_high_low.update_traces(
        line=dict(width=2)
    )
    st.plotly_chart(
        fig_high_low,
        use_container_width=True,
        config={"displayModeBar": False}
    )
# 📦 2. Yearly Coffee Trading Volume Trend
with col2:
    df_volume = filtered_df.copy()
    df_volume["Trade Date"] = pd.to_datetime(
        df_volume["Trade Date"],
        errors="coerce"
    )

    df_volume["Year"] = (
        df_volume["Trade Date"]
        .dt.year
    )

    df_yearly_volume = (
        df_volume.groupby("Year")["Volume (Ton)"]
        .sum()
        .reset_index()
    )

    fig_yearly_volume = px.bar(
        df_yearly_volume,
        x="Year",
        y="Volume (Ton)",
        title="📦 Volume Trend"
    )

    fig_yearly_volume.update_layout(
        template="plotly_white",
        height=200,
        plot_bgcolor="#FAF6EE",
        paper_bgcolor="#FAF6EE",
        yaxis=dict(showgrid=False),
        xaxis=dict(type="category"),
        title_x=0.15,
        margin=dict(t=40, b=5, l=0, r=0)
    )
    fig_yearly_volume.update_traces(
        marker_color="#0F172A"
    )
    st.plotly_chart(
        fig_yearly_volume,
        use_container_width=True,
        config={"displayModeBar": False}
    )
# 📅 3. Monthly Price Seasonality
with col3:
    df_season = filtered_df.copy()
    df_season["Trade Date"] = pd.to_datetime(
        df_season["Trade Date"],
        errors="coerce"
    )
    df_season["Month_Name"] = (
        df_season["Trade Date"]
        .dt.month_name()
    )
    month_order = [
        "January", "February", "March", "April",
        "May", "June", "July", "August",
        "September", "October", "November", "December"
    ]
    monthly_pattern = (
        df_season.groupby("Month_Name")["Closing Price"]
        .mean()
        .reset_index()
    )
    monthly_pattern["Month_Name"] = pd.Categorical(
        monthly_pattern["Month_Name"],
        categories=month_order,
        ordered=True
    )
    monthly_pattern = monthly_pattern.sort_values(
        "Month_Name"
    )
    fig_seasonality = px.line(
        monthly_pattern,
        x="Month_Name",
        y="Closing Price",
        markers=True,
        title="📅 Seasonality"
    )

    fig_seasonality.update_traces(
        line=dict(
            color="#2C1D11",
            width=2
        )
    )

    fig_seasonality.update_layout(
        template="plotly_white",
        height=200,
        plot_bgcolor="#F5F1E8",
        paper_bgcolor="#F5F1E8",
        yaxis=dict(showgrid=False),
        title_x=0.15,
        margin=dict(t=40, b=5, l=0, r=0)
    )

    st.plotly_chart(
        fig_seasonality,
        use_container_width=True,
        config={"displayModeBar": False}
    )
# 📊 4. Price Volatility by Coffee Symbol
# GRAPH 8: TOP 5 GAINERS (HORIZONTAL BAR CHART - DARK BROWN)
with col4:  # 4th column in Row 2
    df_gainer = filtered_df.copy()

    if "Percentage Change (%)" not in df_gainer.columns:
        df_gainer["Percentage Change (%)"] = (
            (df_gainer["Closing Price"] - df_gainer["Opening Price"]) / df_gainer["Opening Price"]
        ) * 100

    # 1. Select Top 5 Symbols by average percentage growth
    top_gainers_df = (
        df_gainer.groupby("Symbol")["Percentage Change (%)"]
        .mean()
        .reset_index()
        .sort_values("Percentage Change (%)", ascending=True)  # Horizontal chart requires ascending order for pr
        .tail(5)  # Top 5
    )

    # 2. Build Horizontal Bar Chart
    fig_gainers = px.bar(
        top_gainers_df,
        x="Percentage Change (%)",
        y="Symbol",
        orientation="h",
        title="🚀 Top 5 Gainers (%)"
    )

    # Dark Brown color adjustment
    fig_gainers.update_traces(
        marker_color="#4A2E19",  # Rich Dark Brown / Coffee tone
        texttemplate="%{x:.2f}%",  # በ Bar አሞሌዎች ላይ ፐርሰንቱን ያሳያል
        textposition="outside"
    )

    fig_gainers.update_layout(
        template="plotly_white",
        height=200,
        plot_bgcolor="#F5F1E8",
        paper_bgcolor="#F5F1E8",
        yaxis=dict(showgrid=False),
        xaxis=dict(showgrid=True, gridcolor="#E2E8F0"),
        title_x=0.15,
        margin=dict(t=40, b=10, l=0, r=30)
    )

    st.plotly_chart(
        fig_gainers,
        use_container_width=True,
        config={"displayModeBar": False}
    )
# SIMPLE TIME SERIES FORECASTING (NEXT 3 MONTHS

st.markdown("""
<div style="
    background-color: #4A2C11;
    color:white;
    font-size:15px;
    font-weight:700;
    padding:8px 12px;
    border-radius:8px;
    text-align:center;
    margin-top:0px;
    margin-bottom:15px;
">
☕ 3-Month Price Forecast Model
</div>
""", unsafe_allow_html=True)
# 1. Prepare the filtered data for forecasting

# Create a copy of the currently filtered dataset
forecast_data = filtered_df.copy()

# Make sure Trade Date is stored as a datetime object
forecast_data["Trade Date"] = pd.to_datetime(
    forecast_data["Trade Date"],
    errors="coerce"
)
# Remove rows where Trade Date or Closing Price is missing
forecast_data = forecast_data.dropna(
    subset=["Trade Date", "Closing Price"]
)
# 2. Check whether forecasting data is available
if not forecast_data.empty:
    # 3. Calculate Monthly Average Closing Price
    # Group the data by month and calculate
    
    monthly_price = (
        forecast_data
        .groupby(
            forecast_data["Trade Date"].dt.to_period("M")  # the average closing price for each month
        )["Closing Price"]
        .mean()
        .reset_index()
    )
    # Convert the monthly Period values back to timestamps
    monthly_price["Trade Date"] = (
        monthly_price["Trade Date"]
        .dt.to_timestamp()
    )
    # Sort the data chronologically
    monthly_price = (
        monthly_price
        .sort_values("Trade Date")
        .reset_index(drop=True)
    )
    # 4. Initialize the Forecast DataFrame
    forecast_df = pd.DataFrame()
    # 5. Check for at Least 6 Months of Historical Data
    if len(monthly_price) >= 6:
        # Get the latest available date
        last_date = monthly_price["Trade Date"].iloc[-1]
        # Get the latest average closing price
        last_price = monthly_price["Closing Price"].iloc[-1]
        # 6. Generate the Next 3 Months
        future_dates = [
            last_date + pd.DateOffset(months=i)
            for i in range(1, 4)
        ]
        # 7. Calculate Recent 6-Month Price Momentum
        # Six months contain five month-to-month intervals.
        # Therefore, divide the total price change by 5.
        recent_trend = (
            monthly_price["Closing Price"].iloc[-1]
            - monthly_price["Closing Price"].iloc[-6]
        ) / 5
        # 8. Generate Forecast Prices
        forecast_prices = [
            last_price + (recent_trend * i)
            for i in range(1, 4)
        ]
        # 9. Create Forecast DataFrame
        forecast_df = pd.DataFrame({
            "Trade Date": future_dates,
            "Closing Price": forecast_prices
        })

        # 10. Create Historical + Forecast Chart

        fig_trend = go.Figure()
        # 11. Add Historical Price Line
        fig_trend.add_trace(
            go.Scatter(
                x=monthly_price["Trade Date"],
                y=monthly_price["Closing Price"],
                mode="lines",
                name="Historical Price",
                line=dict(
                    color="#4A2C11",
                    width=2
                    
                )
            )
        )
        # 12. Add Forecast Price Line
        if not forecast_df.empty:

            # Connect the last historical point
            # with the first forecast point

            forecast_x = pd.concat(
                [
                    monthly_price[
                        ["Trade Date"]
                    ].tail(1),

                    forecast_df[
                        ["Trade Date"]
                    ]
                ],
                ignore_index=True
            )["Trade Date"]

            forecast_y = pd.concat(
                [
                    monthly_price[
                        ["Closing Price"]
                    ].tail(1),

                    forecast_df[
                        ["Closing Price"]
                    ]
                ],
                ignore_index=True
            )["Closing Price"]


            fig_trend.add_trace(
                go.Scatter(
                    x=forecast_x,
                    y=forecast_y,
                    mode="lines+markers",
                    name="3-Month Forecast",
                    line=dict(
                        color="#E67E22",
                        width=2,
                        dash="dot",
                        
                    )
                )
            )

        # 13. Configure Chart Layout

        fig_trend.update_layout(

            # Chart title
            title="📈 Coffee Price Trend & 3-Month Forecast",

            # Chart margins
            margin=dict(
                l=10,
                r=10,
                t=40,
                b=10
            ),

            # Chart height
            height=280,

            # X-axis title
            xaxis_title="Date",

            # Y-axis title
            yaxis_title="Average Closing Price",

            # Show unified hover information
            hovermode="x unified",

            # Use a clean Plotly theme
            template="plotly_white",

            # Coffee dashboard background
            plot_bgcolor="#F5F1E8",

            # Paper background
            paper_bgcolor="#F5F1E8",
            yaxis=dict(showgrid=False)
        )
        # 14. Display the Chart
        
        st.plotly_chart(
            fig_trend,
            width="stretch",
            config={
                "displayModeBar": False
            }
        )

    # 15. Handle Insufficient Historical Data
    else:

        st.info(
            "At least 6 months of historical data "
            "is required for the 3-month forecast."
        )
# 16. Handle Empty Filtered Data
else:

    st.info(
        "No sufficient time-series data was found "
        "for the selected filters."
    )
    
# DATASET PREVIEW
with st.expander("📋 Dataset Preview", expanded=False):

    st.markdown(
        """
        <div style="
            font-size: 16px;
            font-weight: 600;
            margin-bottom: 10px;
        ">
            Preview of the filtered dataset
        </div>
        """,
        unsafe_allow_html=True
    )

    st.dataframe(
        filtered_df,
        hide_index=True,
        width="stretch",
        height=300
    )

# 📥 DOWNLOAD FILTERED DATASET
# Encode as UTF-8 to support different characters
csv = filtered_df.to_csv(    # Convert filtered DataFrame into CSV format
    index=False
).encode("utf-8")
# Create download button for users
# Allows users to export filtered coffee market data
st.download_button(
    label="📥 Download Filtered Dataset",
    data=csv,
    file_name="filtered_coffee_data.csv",
    key="download_filtered_data",
)